### ISSUE TITLE
Style of muonic plots

### ISSUE THREAD

**Issue by achim1** [achim1/muonic#31]
* Copied over from confluence
Da Pylab verwendet wird, ist es abhaengig von den Einstellungen in .matplotlibrc, die der User vorgenommen hat. Dies sollte durch das Laden des moduls "rc" und vornehmen der gewuenschten Einstellungen behoben werden.

**Comment by achim1** [comment]
Proposal: Put all the style settings in an own module muonic/gui/style.py and provide possibly two styles:
LargeScreen()
SmallScreen()
also labels and colors should go into style.py

**Comment by hpbretz** [comment]
I like the proposal, I think iit is better to have muonic look identical on all systems.

**Comment by aschulzdesy** [comment]
I agree as well. It's better to have muonic look identical.

**Comment by hpbretz** [comment]
So does muonic now have its own style? The labels seem too big now, at least on my computer. 
![screenshot-muonic](https://cloud.githubusercontent.com/assets/8876379/8250229/0a65143a-1672-11e5-9065-5e40009da1c2.png)

**Comment by hpbretz** [comment]
For me, onesize=20 in styles.py fits all labels and titles on the screen.
