### ISSUE TITLE
Decay plot: fit leads to histogram not shown completely

### ISSUE THREAD

**Issue by aschulzdesy** [achim1/muonic#32]
When fitting the curve to the decay plot the histogram of the events get cut (see plot)

![muonicdecay_daq6936_fit](https://cloud.githubusercontent.com/assets/4849214/7933305/7c43f06e-091e-11e5-8ffd-ce0eb60111c0.png)

**Comment by achim1** [comment]
It seems also weird that the fit did not take into account two more bins to the left. The first bin on the left is excluded, but I am not sure about the other two.

**Comment by aschulzdesy** [comment]
In this case I set the fit range like this, so this is fine. For the CosMO measurements the lower limit should be set to 1.5 us since the MPPC have afterpulses in this time range.

**Comment by achim1** [comment]
Ok, I forgot about that. The original issue should be fixed by now, but requires a test. I updated pypi accordingly, new version is now 2.0.7

**Comment by achim1** [comment]
Seems to be fine now (poorly tested with fit to 5 muons)
