### ISSUE TITLE
"scaler" is not an english word 

### ISSUE THREAD

**Issue by aschulzdesy** [achim1/muonic#35]
In the "Muon Rates" tab in the table the counts are labelled "scaler" 
Scaler is not the proper word (or I don't get it) dictioniaries say: 
http://www.dict.cc/?s=scaler 
something for a dentist?! 
http://dict.leo.org/ende/index_en.html#/search=scaler&searchLoc=0&resultOrder=basic&multiwordShowSingle=on 

Probably it was supposed to be "scalar"? But this is not intuitive either and rather mathematical (I think).
 
Could we change it to "counts" ? 

and when changing the labelling: could we change from Hz to 1/s. Many teachers and students say that it is really confusing. 

and is there a reason for showing the "max rate". Most of the times it does not make sense and shows values around several hundred thousand uo tp 1 million. (I think due to short time intervals in the first moments turning it on .

**Comment by achim1** [comment]
It was originally meant to be "scalars", as you said. But I agree, it is not intuitive and probably does not even make sense, it originated from the qnet windows software. Will change to counts.
The max rate thing is a control field, to check for peaks in the rate graph, which probably distort the average rate calculation. That sometimes happened during the middle of a measurement and then it was useful to see an indication that something went wrong and the average rate might not be useful (at least so I was told). Should we try to make it more meaningful ( and check the first moments issue) or remove it as nobody is using it anyway?

**Comment by hpbretz** [comment]
I think having the max rate value makes sense and can help when you return to muonic after a long measurement. But those extremely high values probably come from the first bin or so and don't really correspond to anything meaningful or can help debug the measurement. If we can fix that, we could leave the max rate field in the widget.

**Comment by aschulzdesy** [comment]
Hi, 
great, the students in the lab also said that counts is better than scaler. 
But they just noticed that Hz is gone nearly everywhere, but on the plot the axis still says Hz instead of 1/s which is confusing.
