### ISSUE TITLE
'warning: 2D hist input should be....'  when starting muoinc

### ISSUE THREAD

**Issue by aschulzdesy** [achim1/muonic#40]
INFO:9236:DaqConnection:get_port:50:Daq found at /dev/ttyUSB0
INFO:9236:DaqConnection:get_port:51:trying to connect...
INFO:9236:DaqConnection:get_port:62:Successfully connected to serial port
INFO:9236:MainWindow:__init__:173:Timewindow is 5.00
/usr/lib/pymodules/python2.7/matplotlib/axes.py:8261: UserWarning: 2D hist input should be nsamples x nvariables;
 this looks transposed (shape is 0 x 1)
  'this looks transposed (shape is %d x %d)' % x.shape[::-1])
INFO:9236:PulseAnalyzer:__init__:313:Initializing decay trigger, setting triggerwindow to 10000
INFO:9236:PulseAnalyzer:__init__:275:Velocity trigger initialized

**Comment by achim1** [comment]
We have this since very long - I don't know what it means and it never seemed to be related to any other tning

**Comment by achim1** [comment]
Matplotlib does not like initializing a hist with an empty array - related to #47
