### ISSUE TITLE
Velocity measurement: attribute error  'QTabWidget' object has no attribute 'pulseextractor'.

### ISSUE THREAD

**Issue by aschulzdesy** [achim1/muonic#41]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/muonic/gui/MuonicWidgets.py", line 774, in activateVelocityClicked
    self.pulsefile = self.parentWidget().parentWidget().pulseextractor.pulsefile
AttributeError: 'QTabWidget' object has no attribute 'pulseextractor'

I#m not sure if it has a bad effect on the measurement, does not look like it.

**Comment by achim1** [comment]
Might have prevented some file to be written...
