### ISSUE TITLE
flight time measurement: no fitline shown

### ISSUE THREAD

**Issue by aschulzdesy** [achim1/muonic#42]
when activating the flight time measurement and clicking "fit" no fitline is shown, only the triangles on top of the histogram. 
![muonvelocitydistribution_fit](https://cloud.githubusercontent.com/assets/4849214/8006089/c84b0474-0b90-11e5-862d-d93ca5331739.png)

**Comment by achim1** [comment]
The problem is that the fit is bad -> it basically failed and is not even able to calculate its chi squared/ndf ("nan"). Not sure how to fix it at the moment

**Comment by achim1** [comment]
Fixed! The Gaussian was broken (had only two instead of three parameters as intended).
This fix should go to any branch

**Comment by aschulzdesy** [comment]
Hi Achim, in which version is this fixed? I had a problem today with version 2.0.10. See plot: 
![velocity_nofit](https://cloud.githubusercontent.com/assets/4849214/8284461/4f21e07a-18fd-11e5-96f1-959c07eb8c1d.png)

**Comment by achim1** [comment]
> 2.0.11 ^^
> ..and we are at 2.0.12 now..

2015-06-22 16:40 GMT+02:00 aschulzdesy notifications@github.com:

**Comment by achim1** [comment]
> < > -> >=   ^^

2015-06-22 21:14 GMT+02:00 Achim Stößl achim.stoessl@gmail.com:

**Comment by aschulzdesy** [comment]
it's working now :) 
![muonvelocityfit](https://cloud.githubusercontent.com/assets/4849214/8410058/2cfd8e98-1e7c-11e5-8f3f-9307c90ba5c9.png)
