### ISSUE TITLE
Muon rates: daq time sometimes not shown in multiplicities of 5s 

### ISSUE THREAD

**Issue by aschulzdesy** [achim1/muonic#43]
In the muon rates tab, usually the first time bin which is shown at daq time is something arbitrary, which is fine. Most of the times the second bin is just 5.00 s and all other daq times are multiplicities of 5 (which I think is how it is planned). 
But from time to time this is not the case and it stays with 5.18 and then 10.18, ... I did not find out when this is the case. I got the impression that it is mostly the case when the first time is smaller than 2s, but this can also be a chance coincidence.

**Comment by hpbretz** [comment]
This should be fixed by now in https://github.com/achim1/muonic/commit/f55fae0365b7774fd09ddfe281a927785f195cdc
