### ISSUE TITLE
'Help section' neither technical documentation nor Manual open

### ISSUE THREAD

**Issue by aschulzdesy** [achim1/muonic#44]
When clicking on help and manual nothing happens. The terminal says:

INFO:3440:MainWindow:sphinxdoc_menu:433:opening docs from /usr/local/lib/python2.7/dist-packages/muonic/gui/../docs/html/index.html
gvfs-open: /usr/local/lib/python2.7/dist-packages/muonic/gui/../docs/html/index.html: Fehler beim Öffnen des Ortes: Fehler beim Holen der Informationen für Datei »/usr/local/lib/python2.7/dist-packages/muonic/docs/html/index.html«: Datei oder Verzeichnis nicht gefunden
INFO:3440:MainWindow:manualdoc_menu:444:opening docs from /usr/local/lib/python2.7/dist-packages/muonic/gui/../docs/html/manual.pdf

gvfs-open: /usr/local/lib/python2.7/dist-packages/muonic/gui/../docs/html/index.html: Fehler beim Öffnen des Ortes: Fehler beim Holen der Informationen für Datei »/usr/local/lib/python2.7/dist-packages/muonic/docs/html/index.html«: Datei oder Verzeichnis nicht gefunden

**Comment by achim1** [comment]
Related to #36

**Comment by achim1** [comment]
Technical documentation fixed, see #36 which is now closed

**Comment by aschulzdesy** [comment]
It's still broken in version 2.0.12

**Comment by aschulzdesy** [comment]
Ok, so it's only about the Manual. The place where we keep the up-to-date manual is the  "physik.begreifen" page. I think the easiest way is to have a browser open which links to http://physik-begreifen-zeuthen.desy.de/angebote/kosmische_teilchen/schuelerexperimente/cosmo_experiment/index_ger.html
