### ISSUE TITLE
daq time does not start with "start run" when starting for the first time

### ISSUE THREAD

**Issue by aschulzdesy** [achim1/muonic#53]
In version 2.0.11 we have an issue which was not there in version 2.0.2 (I think) 

If Muonic is started for the first time and "start run" is clicked it happens often that the time shown is 100s or more, not 5 s as expected. I think it is the time where the daq card was started and not the run. 

When stopping the run and restarting it is fine again.

**Comment by hpbretz** [comment]
The time you mean is daq time, right?

**Comment by aschulzdesy** [comment]
yes, I mean the daq time.

**Comment by hpbretz** [comment]
It is currently the time between the initiation of the rate widget and the point when you click on Start, which makes no sense. I'll fix it so that it counts from the time when you start the meausurement.

**Comment by hpbretz** [comment]
I have to correct myself here: Muonic starts counting muons from the moment it is started. If I force the first time bin to be about 5s (i.e. to start measuring time only from the moment you click on start), the first bin will be wrong and show a higher rate. I would have to change the way muonic communicates with the daq to correct that.

The values shown in the rate plot are maybe not exactly what you would expect (measurement from the start of muonic, not the click on the start button), but they are consistent and correct.

Should this still be changed?

**Comment by aschulzdesy** [comment]
What I mean is (I think) related to the "max rate" issue. It was fine before, should be not more than 10 commits (confirmed by Achim).  
Whether the first bin actually has 5 s or not does not matter much I think. But the problem is that a high value of e.g. 10000 in rate changes the mean drastically which is not wanted.

**Comment by aschulzdesy** [comment]
an example is here: 
![bildschirmfoto vom 2015-07-21 10_32_16](https://cloud.githubusercontent.com/assets/4849214/8796317/1b62d0f2-2f94-11e5-98a5-a8b107cfb444.png)

**Comment by hpbretz** [comment]
Are there any steps to reproduce this? I was testing this issue, and found the opposite. Muonic is initiated with a total count of zero muons, while the daq keeps counting them. So the first Bin has sometimes too many muons and a high rate.

**Comment by aschulzdesy** [comment]
i just started another run and there it is the case with too many: 
![bildschirmfoto vom 2015-07-21 10_48_21](https://cloud.githubusercontent.com/assets/4849214/8796608/31fce86e-2f96-11e5-9f05-a7cfa1d000a9.png)

**Comment by aschulzdesy** [comment]
I tested it with starting and stopping runs and restarting and it looks fine now

**Comment by hpbretz** [comment]
Then fixed in https://github.com/achim1/muonic/commit/f55fae0365b7774fd09ddfe281a927785f195cdc
