### ISSUE TITLE
Is it wanted that the trigger is "off" (so not displayed) if coincidence is set to single?

### ISSUE THREAD

**Issue by aschulzdesy** [achim1/muonic#55]
If one sets the setting to single, the trigger is not displayed. Which does not make sense to me, I thought that the trigger is then set to any event, so should have a much higher rate. 
I think this was different before.

**Comment by hpbretz** [comment]
I agree, it also helps to demonstrate how the trigger works. I removed the check that disables the trigger in case of single coincidence. Needs test with a real detector, the simulation mode ignores the settings apparently.

**Comment by achim1** [comment]
Yes it was **explicitely** requested and we implemented it. There was also a long discussion at that time what trigger even means and how to demonstrate what a trigger is to students..
We probably should not change it, as people are used to the behaviour - but that's only my 2 cents

**Comment by hpbretz** [comment]
I wasn't part of that discussion, and I don't want to start it now. So someone just decide how we should do it, I can quickly change it back.

**Comment by aschulzdesy** [comment]
I also was not part of the discussion. But just spoke to Caro and especially since we changed "coincidence" to "trigger condition" she agrees with having it as I proposed. So trigger also give a value when set tot single. So I think it is fine like it is implemented in version 2.0.20.
