### ISSUE TITLE
some problem about installing the muonic

### ISSUE THREAD

**Issue by johnny8266** [achim1/muonic#60]
Hello, I am a college student and my teacher gave me the muon detector to do some experiment. He also told me to install the muonic to analyze the data. However, I met some problem(please see the attachment). I follow the steps to install the muonic ,using the command -> python setup.py install, but it didn't work when I want to start the muonic. Can anyone help me to solve this problem??
![2015-08-01 22 39 32](https://cloud.githubusercontent.com/assets/13598774/9022385/e2ac169a-38a5-11e5-9a7f-dca3292ce22e.png)

**Comment by hpbretz** [comment]
Hi, can you check the environment variable PYTHONPATH and PATH?

You can do so by typing 

`echo $PYTHONPATH`

in your console

**Comment by achim1** [comment]
Can you try "import muonic" in a python console?
If everything fails, what mostly works is to move bin/muonic one folder up and start it from there without any installing process.
Also, you can try install it via "pip install muonic"
And if you don't have root access to the system, then try "pip install muonic --user" 
Let us know how it goes.

**Comment by hpbretz** [comment]
Hi Johnny, can you please comment if this is still an issue?

**Comment by johnny8266** [comment]
I'am sorry, I didn't do it on purpose. My teacher suggested me to install the older version of the muonic,muonic 2.0.6, and it could work smoothly so I forget to comment here. But I was still confused about the fail of installing the latest version of muonic,muonic 2.0.20 , I will try the methods you provided. If there's anything, I will comment here

**Comment by hpbretz** [comment]
Did you install muonic 2.0.6 with the very same method and it immediately worked? Is there anything you did differently between muonic 2.0.6 and 2.0.20? Because both should work and the last one has a few bugs removed.

**Comment by johnny8266** [comment]
Yes, I installed them with the same method, using the "python setup.py install" ,and I was asked for installing a python package when I want to run the muonic 2.0.6. After I installed the that package, I could use the muonic 2.0.6. But I wasn't asked for installing that python package when I tried to run the muonic 2.0.20. I would try try to find which package I installed and also try to installed the muonic 2.0.20 again .

By the way, our lab member, he used the different linux version with mine, also failed to install the muonic 2.0.20. However, he installed the muonic 2.0.6 successfully

**Comment by johnny8266** [comment]
Hello, I removed the muonic 2.0.6 and installed the muonic 2.0.20, using the python setup.py install. Surprisingly, the muonic 2.0.20 could run(please see the attachment). I thought the key point is the python package ,python-tk, because I was asked for installed this package when I want to start the muonic 2.0.6.

Thanks for your help!!
![2015-08-13 18 41 51](https://cloud.githubusercontent.com/assets/13598774/9248038/1d7b498c-41eb-11e5-9d00-72658d36092e.png)

**Comment by hpbretz** [comment]
Ok, glad it is up and running.

**Comment by johnny8266** [comment]
: )

2015-08-20 21:01 GMT+08:00 hpbretz notifications@github.com:
